version: '2'

services:

  backend:
    build:
      context: .
    tty: true
    ports:
      - "7000:7000"
    command: npm start
    environment:
      - NODE_ENV=development
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
